name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Test
        run: xvfb-run yarn test
