name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: node:10.16

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
