name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: node:10.16

    steps:
      - name: Install native packages
        run: >
          apt-get update && apt-get install -y
          libnss3
          xvfb
      - name: Configure Virtual Display Server
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
